name: 'Run Il2CppDumper'
description: 'Run Il2CppDumper in GitHub Actions automatically'
inputs:
  exec_path:
    description: 'Path to executable'
    required: true
  metadata_path:
    description: 'Path to global-metadata.dat'
    required: true
    default: 'global-metadata.dat'
  output_dir:
    description: 'Output directory'
    required: false
    default: '.'
  il2cpp_dumper_version:
    description: 'Il2CppDumper version to use'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Download Release Asset
      id: download_release_asset
      uses: i3h/download-release-asset@v1
      working-directory: ${{ github.action_path }}
      with:
        owner: Perfare
        repo: Il2CppDumper
        tag: ${{ inputs.il2cpp_dumper_version }}
        file: /Il2CppDumper-netcore-(.*?)\.zip/
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - run: unzip Il2CppDumper-netcore-*.zip
      working-directory: ${{ github.action_path }}
      shell: bash
    - run: echo Running Il2CppDumper for ${{ inputs.exec_path }} with metadata ${{ inputs.metadata_path }} \
          && dotnet ${{ github.action_path }}/Il2CppDumper.dll ${{ inputs.exec_path }} ${{ inputs.metadata_path }} ${{ inputs.output_dir }}
      shell: bash