# vim: expandtab tabstop=2 shiftwidth=2
name: Run Il2CppDumper

on: 
  push:
  workflow_dispatch:
    inputs:
      unk:
  repository_dispatch:

env:
  exec_path: "allstars"
  metadata_path: 'global-metadata.dat'
  output_dir: "."
  il2cpp_dumper_version: 'latest'

defaults:
  run:
    shell: bash

jobs:
  metadata_decode:
    name: 'Do Il2CppDumper'
    runs-on: "ubuntu-latest"
    steps:
      - uses: i3h/download-release-asset@v1
        name: Download Il2CppDumper
        with:
          owner: Perfare
          repo: Il2CppDumper
          tag: ${{ env.il2cpp_dumper_version }}
          file: /Il2CppDumper-netcore-(.*?)\.zip/
      - run: mkdir /tmp/Il2CppDumper && mv Il2CppDumper-netcore-*.zip /tmp/Il2CppDumper && cd /tmp/Il2CppDumper && unzip Il2CppDumper-netcore-*.zip
      - run: echo Running Il2CppDumper for ${{ env.exec_path }} with metadata ${{ env.metadata_path }} \
            && dotnet /tmp/Il2CppDumper/Il2CppDumper.dll ${{ env.exec_path }} ${{ env.metadata_path }} ${{ env.output_dir }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
