# vim: expandtab tabstop=2 shiftwidth=2
name: Test

on:
  workflow_dispatch:
    inputs:
      unk:
  
jobs:
  test:
    name: 'Test Action'
    runs-on: "windows-latest"
    steps:
      - uses: NyaMisty/AutoIl2CppDumper@master
        with:
          exec_path: "111"
          metadata_path: "222"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3